altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  9082367f-eaad-4f4f-aee1-c863257070cf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-24T00:37:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3369eb57-f4e1-4118-b255-6951a6f83c1a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 668f5b7f-821c-4646-aefe-3a777cba5ed6
        userCondition: null
fs: default
handle: pokemon
name: Pokemon
sortOrder: 4
subpath: pokemon
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
